### ISSUE TITLE
Decrypt a password on click instead of decrypting everything on activating app

### ISSUE THREAD

**Issue by djibux** [fcturner/passwords#102]
Hello,

Congrats on version 16 which really goes in the right direction.  I have managed to import my 370 passwords :)

I have a performance issue opening the main page.  It takes almost 20 seconds to display the passwords once the page is loaded.  Could that be improved?

I mainly use the app to search for passwords so having only a search field by default could be a simple workaround.

**Comment by fcturner** [comment]
I am really glad that importing now works on so many passwords.

Unfortunately it can't really improve the performance on this amount of passwords, since this is primarily due to the time your server takes to decrypt them all. I use a specific function from RSA Laboratories called PBKDF2 (Password-Based Key Derivation Function 2, or as they call it: [Public-Key Cryptography Standards No. 5 (PKCS #5)](https://tools.ietf.org/html/rfc2898)). In [the second section](https://tools.ietf.org/html/rfc2898#section-2) of its document, you can read about the need for an 'iteration count'. I call it 'rounds'.

The implementation of this is the very same as the answer you seek (to be found [here in passwordservice.php](https://github.com/fcturner/passwords/blob/16.2/service/passwordservice.php#L166-L169)):
```php
/**
 * @var int $rounds The number of rounds to feed into PBKDF2 for key generation
 */
protected $rounds = 100;
```

These rounds are used to encrypt (create) and decrypt (load) your passwords. Changing this will break all your existing passwords but will work on all your new ones. 
Lowering this will make your system faster, but less secure. If you are importing everything anyway, you might want to change this to 50-60 and test your performance again. The downside (besides security) is that you must change this every time you update this app, or else your passwords won't show up (as they cannot be decrypted).

At last, you cannot search passwords if they aren't decrypted. An implementation of decryption-per-passwords seems unnecessary for me at the moment. However, decrypting a password on click will be much safer than decrypting them all while just needing one or two password at a time. For that, I will change this issue's title to make it a suggestion for enhancement, if you're with me :smile:

**Comment by IzK666** [comment]
I have performed a few benchmarks on FF and Chrome over LAN, not internet with 469 passwords.

The results are a bit different depending on which browser I use.
On FF it took about 4 seconds to load the page (request to the server), but the total time after passwords are visible is between 6 and 7 seconds.
On the other hand, Chrome gave me better times. The load with the server is a bit faster, and the passwords are visible after 5 to 6 seconds.
After those tests, I tried to see if there is any change if I move a big number of passwords to the trashbin, which is almost the same what you requested. So I kept 13 passwords visible and 456 passwords where moved to the trashbin.
The time resulting is just the same, which is logical, because all the passwords are loaded (processed by javascript) and only changes how many passwords are viewable or not.

After that, I took my old netbook connected through wifi . The performance of this "computer" is very poor (intel atom N270 1.6Ghz). The browser used is firefox. After 5 seconds all the requests are done, but passwords are visible after 17 seconds!

I can't test it through internet, but certainly the load times will be increased and the last part depends only of your computer and your browser.

**Comment by djibux** [comment]
Hello,

Thanks for the detailed analysis.  I have tried on a much more powerful PC and I confirm that displaying passwords takes around 6 seconds.

Most of that time is spent in the function renderTable.  I have had a quick look but the code is too messy for me to try and change anything.  There is a useless loop (on var j) but that won't impact the performance much.

**Comment by djibux** [comment]
I'm thinking, even though it's a bit old school, pagination could solve that issue.  I don't need all 400 passwords to be displayed.  The first 30 or so would be plenty already…

**Comment by IzK666** [comment]
I don't think is useful. In fact, it's a waste of time (load time) and resources (increase of traffic).
To check that, I performed a new test removing the 456 passwords from trashbin. There is only 13 passwords left (which is much lower than the 30 you suggested).
The load times are between 5 and 6 seconds on my desktop and 10.60 (I do it only once) for the netbook. Both tests on firefox.
To have a better clue what those numbers mean, I timed the files tab where I have 21 files a folder and it required between 6 and 6.5 seconds to be loaded. I'm using owncloud 8.1.4.

Although that, I'm agree with the title.
If passwords are decrypted only on demand, the timer is useless, as the administrator can adjust a session time and, once the time is over, won't load any passwords. As it's an ajax request, should be easy to catch the error and force a reload of the website in case of error. Of course it would mean that the passwords wouldn't be sorted anymore, as every password would look like '***' (or whatever fcturner wants).
As a suggestion, I wish/prefer the old behaviour to view the password and username when clicked and show the edit box only when required by clicking into the pencil.

**Comment by fcturner** [comment]
> @djibux I don't need all 400 passwords to be displayed. The first 30 or so would be plenty already…

This wouldn't make sense if you want to know the password of an entry at the end of the list. Pagination would only slow things down.
<hr>
> @djibux Most of that time is spent in the function renderTable. I have had a quick look but the code is too messy for me to try and change anything.

That's true, I'll admit that. But after the decryption a password is tested for strength, length and classes need to be given to each password (red, orange, green). So this testing consumes a lot of time. The only way I could think of at the time was letting Javascript test the 'quality' of the password by assigning classes. Which is what it does now. That needs to be done after decrypting them. But I have thought of another solution (last part of this post).
<hr>
@IzK666 Maybe want to some benchmarking on the amount of rounds? Then you need to edit the `100` in [service/passwordservice.php](https://github.com/fcturner/passwords/blob/16.2/service/passwordservice.php#L166-L182) line 169 and 178:
```php
L166		/*
L167		 * @var int $rounds The number of rounds to feed into PBKDF2 for key generation
L168		 */
L169		protected $rounds = 100;
L170
L171		/*
L172		 * Constructor!
L173		 *
L174		 * @param string $cipher The MCRYPT_* cypher to use for this instance
L175		 * @param int    $mode   The MCRYPT_MODE_* mode to use for this instance
L176		 * @param int    $rounds The number of PBKDF2 rounds to do on the key
L177		 */
L178		public function __construct($cipher, $mode, $rounds = 100) {
L179			$this->cipher = $cipher;
L180			$this->mode = $mode;
L181			$this->rounds = (int) $rounds;
L182		}
```
Your passwords won't show anymore when you change this number, but will be shown again if you change it back to `100`. Values of 50-60 should really decrease loading times.
<hr>
> @IzK666 As an extra suggestion, I wish/prefer the old behaviour to view the password and username when clicked and show the edit box only when required by clicking into the pencil.

I see what you mean, but others don't like extra clicking and therefore like it more this way and they convinced me to it too. So, for now this will stay the way it is. Sorry...
> @IzK666 If passwords are decrypted only on demand, the timer is useless, ...

That's not entirely true. There must be a defined time limit that allows decrypting. Not all admins will set a session time, but their users do want them.
<hr>
### Another idea:
The downside of decrypting on demand is that you cannot tell if password have a low quality at a first glance. Now you see red, orange and green passwords. The solution might be to update it to the database table (add some columns). That would dramatically decrease the time to load the page!

**Comment by fcturner** [comment]
Filed as #108

**Comment by djibux** [comment]
To me it really makes sense to only load a few.  I really don't care to list all passwords as all I do is search and use passwords.

I like your idea of storing password properties in the database.

**Comment by IzK666** [comment]
I have do the benchmark you requested and it tooks about 6.5s in normal and 5.75s with your modification, which is 0.75 seconds less. This time I did the test with chrome because FF was giving me strange values.

**Comment by fcturner** [comment]
Implemented and released: [v17](https://github.com/fcturner/passwords/releases/tag/17).
