### ISSUE TITLE
Move properties calculation to passwordservice.php

### ISSUE THREAD

**Issue by eglia** [fcturner/passwords#145]
I'm playing around with creating entries via the API. I successfully created a new entry, however I have to explicitly specify every field. IMHO it should behave the same as when I create a new entry in the app, meaning I only have to give a title, username and password and everything else is filled with default/empty values (if not specified) or generated (password strength, last changed...).

And something I wondered for a while: Why are some fields (loginname, password...) present twice (once on the top level and once as part of the properties) but only contain data once?

**Comment by fcturner** [comment]
They exist twice because of previous versions. Please read the changelog of v17, it'll explain it all. 

I will look into the API, that would improve the base code too. I don't know how to do that yet.

**Comment by fcturner** [comment]
From changelog:

Changed database format so that password properties (like strength, length, changed date etc., but also categories and future shared users) will be saved in a hashed, encrypted BLOB format. Database admins will no longer be able to view even the changed date of a password. This improves privacy and greatly reduces the time to load a page too, since Handlebars now loads passwords in conjunction with JSON. This will require users to update their own database data. Therefore, all users will be presented with an update popup after this update (needs to be done only once). After this, the database columns loginname, address and creation_date will be empty and obsolete for those users (but will remain for backwards compatibility).

**Comment by fcturner** [comment]
I've got the solution: calculating strength, testing for lowercase, uppercase, etc. must be moved to the password service: `/service/passwordservice.php`.

This is a major change! I hope to do this for v18 (April/May). So for now, you should only support getting, not putting. Sorry :cry:

**Comment by fcturner** [comment]
As mentioned in #151, this command works:
```
curl -u [user] -H "Content-Type: application/json" -X POST -d "{\"website\":\"00\\\"00\",\"pass\":\"bar\", \"properties\": \"\\\"loginname\\\": \\\"foo\\\", \\\"address\\\": \\\"\\\", \\\"notes\\\": \\\"\\\"\"}" https://[owncloud]/index.php/apps/passwords/api/0.1/passwords
```

I fixed the app so it reads usernames and passwords. Calculation still need to be moved.

**Comment by fcturner** [comment]
Figured it out, moved everything to PHP (locally, not yet Git).
Will be in v18.

**Comment by fcturner** [comment]
#152

**Comment by fcturner** [comment]
All works now.
The `PUT` now works with variables
`create($website, $pass, $loginname, $address, $notes, $category, $deleted)`

So you `PUT` it this way :wink: : 
``` JSON
{
	"website": "testsite.com",
	"pass": "newpassword",
	"loginname": "username",
	"address": "www.testsite.com",
	"notes": "my new notes"
}
```

In command:
```
curl -u [user] -H "Content-Type: application/json" -X POST -d "{\"website\":\"testsite.com\",\"pass\":\"newpassword\",\"loginname\":\"username\",\"address\": \"www.testsite.com\", \"notes\": \"my new notes\"}" https://[owncloud]/index.php/apps/passwords/api/0.1/passwords
```

Works here! With all field calculated (length, strength, everything).

**Comment by eglia** [comment]
Great, works perfectly. Thanks! :muscle:
