### ISSUE TITLE
API create entries containing quotes

### ISSUE THREAD

**Issue by eglia** [fcturner/passwords#151]
It's me again :smile: I'm not sure if this really is a bug, but I noticed the following: If I create an entry via the API (note the website title: 00"00, without the quotation mark it works fine):
```
curl -u [user] -H "Content-Type: application/json" -X POST -d "{\"website\":\"00\\\"00\",\"pass\":\"bar\", \"properties\": \"\\\"loginname\\\": \\\"foo\\\", \\\"address\\\": \\\"\\\", \\\"notes\\\": \\\"\\\"\"}" https://[owncloud]/index.php/apps/passwords/api/0.1/passwords
```
This seems to work fine and I can fetch the created entry with 
```
curl -u [user] https://[owncloud]/index.php/apps/passwords/api/0.1/passwords/[id]

{"id":653,"user_id":"andreas","loginname":"","website":"00\"00","address":"","pass":"bar","properties":"\"loginname\": \"foo\", \"address\": \"\", \"notes\": \"\"","notes":false,"creation_date":"1970-01-01","deleted":"0"}
```
All data is correct. However, when I open the owncloud app, it throws a javascript error
```
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 18 of the JSON data (row 0):
{"website" : "00&quot;00", "pass" : "bar", "loginname&quot;: &quot;foo", "address&quot;: &quot;", "notes&quot;: &quot;", "deleted" : "0", "id" : "653", "user_id" : "andreas"}
```
If I create an entry with the same data in the app, everything works fine and the data returned by the API looks exactly the same.
Any ideas?

**Comment by fcturner** [comment]
Yes, I have an idea :wink: 

But first:
>It's me again :smile:

I'm actually very happy that it's you again! Since you started on your extension, this app has become better already, because of you. I didn't understand much about API's, and now I do better. So thanks!


>I'm not sure if this really is a bug

It is. Some explanation: I validated your JSON string with www.jsonlint.com. A great website for checking the integrity and validity of JSON. 
If I put in your:
```json
{\"website\":\"00\\\"00\",\"pass\":\"bar\", \"properties\": \"\\\"loginname\\\": \\\"foo\\\", \\\"address\\\": \\\"\\\", \\\"notes\\\": \\\"\\\"\"}
```
... I get this error:
```
Error: Parse error on line 1:
{\	"website\":\"00\\
-^
Expecting 'STRING', '}', got 'undefined'
```
But apparently, the API accepts it.The resulting string when you `GET` it is valid JSON:
 ```JSON
{
	"id": 653,
	"user_id": "andreas",
	"loginname": "",
	"website": "00\"00",
	"address": "",
	"pass": "bar",
	"properties": "\"loginname\": \"foo\", \"address\": \"\", \"notes\": \"\"",
	"notes": false,
	"creation_date": "1970-01-01",
	"deleted": "0"
}
```
...which my app reads as:
```JSON
{
	"website": "00&quot;00",
	"pass": "bar",
	"loginname&quot;: &quot;foo",
	"address&quot;: &quot;",
	"notes&quot;: &quot;",
	"deleted": "0",
	"id": "653",
	"user_id": "andreas"
}
```
Now that's invalid, because of the `&quot;` after `loginname`, `address` and `notes`. I will fix it right away by replacing `&quot;` with `"` before further processing.

**Comment by fcturner** [comment]
So I fixed it; it now loads and works. But... the properties obviously do not work; they were never calculated. I need to move these calculations to the server side with PHP; it now happens client side with JS, which is needed for other extensions too: #145.

But you passwords and usernames now load.

**Comment by fcturner** [comment]
(moving classes submitted #145)
