### ISSUE TITLE
Archives of type text/html are not supported

### ISSUE THREAD

**Issue by juhulian** [fcturner/passwords#159]
Hey,
be tring to activate the app on ow9 i got this error message:
Archives of type text/html are not supported
thx help

**Comment by fcturner** [comment]
OwnCloud bug, but they won't fix it. 

You can only install my app outside the App Store. They really messed up the App Store, I cannot and will not support it unless they fix it. Killing for developers, but ownCloud doesn't want to embrace other developers. 

Too bad.

**Comment by tapir** [comment]
Same error message on NextCloud 10 while trying to update it via Apps menu.

**Comment by fcturner** [comment]
Still same story. 
Please read the installation part in the manual how to quickly update the app, without compromising all your server info to ownCloud GmbH. 

As long as you use the App Store, they track your movements. They have no privacy statement, so that's no different than Google for me. And I don't want to circumvent the way GitHub works, so they really need to review the code.

**Comment by fcturner** [comment]
https://github.com/fcturner/passwords#installation
