### ISSUE TITLE
Data loss after OC upgrade

### ISSUE THREAD

**Issue by viki53** [fcturner/passwords#189]
Hi,

I recently upgraded to OwnCloud 9.0.1 and after some shenanigans (an app threw a fatal error that was hard to find) I finally managed to access the Web interface again.

But now I've lost all my passwords: it says I don't have any, but I had about ten lines in that list just a week ago.

Any idea how this was lost? 

Any chance I can get them back somewhere (database or raw files on the serve)?

**Comment by fcturner** [comment]
That's nasty!

Does the database table oc_passwords still exist? Do you know how to check that?

**Comment by viki53** [comment]
Yes, database is still here and everything still seems to be in this table. That's good news!

**Comment by fcturner** [comment]
Great, then everything will be just fine. 

Version 17.1 and below do not work on OC9. So I think you're on an older Passwords version. 
Please download v18 and enjoy password sharing too!

**Comment by viki53** [comment]
Oh right, I forgot I had to update manually this app!

The apps admin panel doesn't indicate there's an update, it's a little complicated to be aware of the new versions…

**Comment by fcturner** [comment]
Yes, not really convenient. You can view updates when going to the 'Apps' app as admin (with the plus icon). 

But due to privacy concerns and not taking app developers seriously, I refuse to support updating from the web interface. It can be solved by ownCloud easily, but they don't want to. 

Thinking of it, I can make a function that checks if there's an update available and show it on the Admin page! Far better than their own system. Great idea!

**Comment by viki53** [comment]
That would be great!

And there's the *Notifications* app that could be helpful for that too, I guess.
