### ISSUE TITLE
Create possibility to export/print entries

### ISSUE THREAD

**Issue by Tramour** [fcturner/passwords#21]
First things first: Great app and very useful.

One tiny suggestion from me:
For backup reasons or simply to have the possibility to transfer data I'd welcome an export or print functionality.

**Comment by fcturner** [comment]
Thank you!

The only suggestion I can think of, is to create a password encrypted archive with all your passwords (using 7-zip and its AES-256 encryption for example). Otherwise, it would be very similar to write your passwords down on a note and leave it in a desk for burglars like many people do :cry: 

I just read that LastPass *does* support this... I really sounds awkward to me. A backup sound good, but it should always be encrypted with a master key in my opinion. So maybe an option to create a backup and download it right away.
Sound like a lot of work, but I like the idea. So thanks again :smile:

**Comment by Tramour** [comment]
No objection to an encrypted export as an compressed archive. Sounds good to me. But for whatever reasons my OC might be down I see the necessitiy for an local backup which I can access.

PS: For a print I have a safe at home ;-)

**Comment by fcturner** [comment]
Fixed with the 8.0.6 release (https://github.com/fcturner/passwords/commit/aa76297a04e9f3d18bf5ff189aa8bbc531e7a174)

Using encryption (like 7zip) make the app dependent on other packages. As a solution, I added the option to forbid this backups on the Admin page.
