### ISSUE TITLE
Transfer ownership of Passwords

### ISSUE THREAD

**Issue by benedikt-d** [fcturner/passwords#213]
Would be great if it would be possible to transfer the ownership of a password to someone else. So a password I created can be edited by someone else.

**Comment by fcturner** [comment]
Good point, but I'll implement this using #198, so you can clone a password and recreate it yourself. 

I cannot transfer ownership, simply because the encryption uses part of the data from the user who creates a password as part of the block cipher. It cannot be decrypted if the user who created the password isn't logged in. That's just impossible and so it should be :wink:
