### ISSUE TITLE
After update from 17.2 to 18.0 only 5 passwords are shown

### ISSUE THREAD

**Issue by ShozenOne** [fcturner/passwords#253]
After update to version 18.0 in the passwords app nothing is shown...

![owncloud_passwords_screen1](https://cloud.githubusercontent.com/assets/21957401/18211351/85b60b5e-713d-11e6-8ebf-3273bb0da5cb.jpg)

After select "active passwords" at least 5 passwords are shown...

![owncloud_passwords_screen2](https://cloud.githubusercontent.com/assets/21957401/18211360/8a931d88-713d-11e6-9662-2d3ef5836b2a.jpg)

Perhaps someone has a workaround for this bug!?
In the database all entries are existing.

**Comment by fcturner** [comment]
Hello! I'm sorry you run into this trouble.
Can you please post the output of the ownCloud log and the browsers log?

**Comment by ShozenOne** [comment]
Hi! Please find attached the log files. 
[owncloud_browser.txt](https://github.com/fcturner/passwords/files/465339/owncloud_browser.txt)
[owncloud.txt](https://github.com/fcturner/passwords/files/465340/owncloud.txt)

**Comment by fcturner** [comment]
Ah, this is already fixed in v19. It gave an error when creating an avatar.

Please download the latest master ([zip](../archive/master.zip) or [tarball](../archive/master.tar.gz)). We are now on the fifth beta (version number 19-beta5). 

 I will release it soon. I need LDAP support first and I'm testing this with some others extensively right now.

**Comment by ShozenOne** [comment]
Same problem with version 19.

This error based on the entry `'enable_avatars' => false,` in the config.php.
Maybe it will be fixed in the next version!?
