### ISSUE TITLE
Stripped entries in website column might lead to unencrypted page linking (HTTPS -> HTTP)

### ISSUE THREAD

**Issue by godfuture** [fcturner/passwords#26]
I just tested to add my first password. I noticed that the site I have entered with HTTPS was stored without HTTPS. When following the site by clicking on it, I am redirected to its non protected webpage. 

Why is HTTPS string removed on site URI? I guess HTTPS does make sense though and if the stored webpage doesn't auto redirect to HTTPS, you will end up unencrypted.

Please allow HTTPS prefix in site field.

**Comment by fcturner** [comment]
Thank you for this issue.

Former issue #23 would fix this (great work by @IzK666).

I wil implement this as soon as I am done with the sharing option. Otherwise, multiple test versions might interfere with each other on my machine. Stay tuned! Shouldn't take long!

**Comment by Tramour** [comment]
@fcturner Tested and it works like a charm +1

**Comment by fcturner** [comment]
I didn't tell you the reason why I created it this way.

So here's the explanation:
It has to do with the sorting function of the table. If you have a table with some websites starting with `https://` and others with `https://www.`, the sorting might become:

1. `https://test.com`
2. `https://www.abc.com`

Instead of 

1. `abc.com`
2. `test.com`

(Hence, `https://www.test.com` might be unsupported by `test.com`)


But, a hidden column containing the full link might actually overcome this. So I am very grateful for the work @IzK666 did, which will lead to implementation as soon as I finish the share-ish part, so said :smile:

**Comment by fcturner** [comment]
Great, thanks for testing!!

**Comment by fcturner** [comment]
Fixed with the 8.0.6 release (https://github.com/fcturner/passwords/commit/aa76297a04e9f3d18bf5ff189aa8bbc531e7a174)
