### ISSUE TITLE
REST API: Notes does not get properly escaped

### ISSUE THREAD

**Issue by intirix** [fcturner/passwords#273]
If the notes section of a password contains a backslash, then the password will cause a parse error when accessing it via the REST API.  It seems like the notes field is not being properly escaped when creating the properties field.  Below is an example, but Github might mangle it.

Notes is "test \ test"

Here is what I get.  The value of "properties" is {"notes" : "test \ test"} which is not valid json
`{
 "properties": "{\"notes\" : \"test \\ test\"}"
}
`

Here is what it should be.  The value of "properties" is {"notes" : "test \\ test"}
`{
 "properties": "{\"notes\" : \"test \\\\ test\"}"
}
`

https://github.com/intirix/cloudpasswordmanager/issues/9

**Comment by fcturner** [comment]
Thanks for getting to me. On the website interface it does work. If I would change the API, it would also change the website part. The JSON part is awful, as I needed to support MySQL, SQLite and PostGreSQL. They are so different that I couldn't save it as valid JSON to the databases. That's why it is being saved as text in an awkward way. Another thing is, if I created different database columns for each property, decryption would take a long time and I would have lost the freedom in adding or deleting other properties (like sharing, I added that later) without altering the database structure.

Maybe you can use part of my JS code to escape it before it serves to your app. Apparently, if you would replace all property fields consisting of `\\` with `\\\\` you're good to go.

Does that help?

**Comment by intirix** [comment]
I can manipulate the "json" to get it to work.  I will do it in the exception block so if you ever figure out how to solve the issue in the future, existing versions of my app won't have an issue.  My only concern is this might not be the only pattern that breaks.  I might get a report periodically about various other patterns that break.
