### ISSUE TITLE
Nextcloud 11 JSON parse: expected double-quoted property

### ISSUE THREAD

**Issue by kbaegis** [fcturner/passwords#297]
Every time I navigate to the password app, I get prompted by 4+ of the following:
SyntaxError: JSON.parse: expected double-quoted property name at line 1 column 42 of the JSON data (row x):
{"website" : "<user>", "pass" : "false&quot;, false, &quot;deleted" : "false", "id" : "<id>", "user_id" : "<user>"}

**Comment by fcturner** [comment]
That's an odd string. Can you supply me with the whole string? Or is this the whole string?

**Comment by fcturner** [comment]
Thanks for reporting! 👍

**Comment by fcturner** [comment]
Duplicate of #296

**Comment by fcturner** [comment]
This should now be fixed in the latest master. **Please try it and report back.** Thanks!

#### Package download
(remember to rename the folder to `passwords`)
[:package:ZIP file](../archive/master.zip)
[:package:TAR file](../archive/master.tar.gz)

#### Command line 
(assuming `/var/www/owncloud/` as your root location)
 ```sh
rm -rf /var/www/owncloud/apps/passwords
git clone https://github.com/fcturner/passwords.git /var/www/owncloud/apps/passwords
```

**Comment by elbotho** [comment]
Issue is indeed resolved for me. Thank you!

**Comment by fcturner** [comment]
:+1:
