### ISSUE TITLE
Publishing to new Nextcloud App Store?

### ISSUE THREAD

**Issue by e-alfred** [fcturner/passwords#302]
Hello,

now that Nextcloud has its own App Store, do you think this one does a better job to get your app published there? From the docs it says that it uses Git tags and packages everything automatically:

> Your app’s source code is hosted on GitHub or a similar service
You should use Git tags to create new releases on these services
Archives are typically created automatically for you. If you require compilation or other transformations like minification, you should upload a pre-built archive to the appropriate releases page

from https://nextcloudappstore.readthedocs.io/en/latest/developer.html

**Comment by fcturner** [comment]
Nice idea, but I don't like that idea. There's no privacy statement, and I don't like one-way policies where app stores can track my moves (who knows?) but I can't track theirs. Not much of an App Store fan, I like my privacy.
Then there's this thing, it's not easy AT ALL to publish on that app store, read this: http://nextcloudappstore.readthedocs.io/en/latest/developer.html#publishing-apps-on-the-app-store. Tremendous amount of work.
It makes me wonder why there wouldn't advice to use Git, it doesn't get much simpler:
```
rm -rf /var/www/owncloud/apps/passwords
git clone --branch 19 https://github.com/fcturner/passwords.git /var/www/owncloud/apps/passwords
```
And for the few that cannot use Git, downloading a zip file and replacing the old folder isn't much work too.

I'm not even a NextCloud fan, giving the fact that I'm solving multiple issues for this app to support NC11 because they lack to document notes for app developers. I have to let others down because they migrated to NextCloud. And I really don't like *that*. 

I'm sorry, I'm a bit frustrated about that at the moment. Maybe I'll find NC useful over OC in the new year. For now, I certainly don't. I hear others complaining constantly about the same. NC11 is just premature in my opinion.

**Comment by rugk** [comment]
Please do publish your app in the NextCloud store. I suspect most users install apps from their, so they cannot even find your app when it is not there.

And the things you have to do when publishing an app are done for a reason: security.
If you say AppStores violate your privacy that's fine, of course, but don't force this aspects on other users. Each NextCloud admin can decide by themselves whether to use the app store.

**Comment by fcturner** [comment]
Disagreed. I don't like NextCloud, and I don't like setting aside my principles. Supporting NC is already almost too tough to do voluntarily. Dreadful fork of OC if you ask me. Yet. 
(I do hope that it will improve however)
