### ISSUE TITLE
Share passwords between ownCloud users

### ISSUE THREAD

**Issue by ronoliverclarin** [fcturner/passwords#4]
Is there any roadmap or possibility to share the passwords in specific user?

**Comment by fcturner** [comment]
Hmmm, yes that might actually be a good idea, but a lot of work. I will look into it! Thanks for the idea!!

**Comment by fcturner** [comment]
I thought this thru. I don't think this is wise to implement for the following reasons:
- every user should have there own passwords. Since my app doesn't support editing passwords (only creating and deleting), there is no need to share since such password cannot be edited and new passwords must be shared every time.
- passwords are decrypted with a specific key for each password, including a reference to the username. Decryption is impossible for another user, so this just won't work. One solution is a second database table with userid's of the one sharing and the one receiving the share. These are visible to administrators. To me, that's not safe enough.

**Comment by ronoliverclarin** [comment]
Hi @fcturner ,

The share feature within owncloud is highly recommended. Especially, for a very small startup team like us that we are using client's accounts. You can check other password management like lastpass and Team Password Manager.

If this is possible, I will use this module as soon as possible. But now, I am finding alternative ways to  make it happen in low or free(will donate a little) platform.

**Comment by fcturner** [comment]
Alright, I will look into the possibilities. But it will take some time :)

**Comment by fcturner** [comment]
I tried, but this is too hard for me... Anyone who want to pull this one off, be my guest :smile:

**Comment by fcturner** [comment]
- [X] Find out how to share items at database level
 - This can be done with `oc_share` where all shared items are stored. `Share_type` will be 'Password'
- [X] Edit SQL-queries so that shared items are loaded into table
- [X] Create *Shared with* column and populate it with `handlebars`
- [X] Edit JavaScript to disable deletion of shared passwords (only the owner should be able to do so)
- [ ] Make use of ownCloud's share dialog and use it to make database edits
 - [ ] Get list of all users
 - [ ] Option to set share
 - [ ] Option to unset share

**Comment by ffflorian** [comment]
For my team it would be a huge improvement. So I'm giving it a huge +1!

**Comment by jasonfharris** [comment]
+1 for this feature from me...

**Comment by fcturner** [comment]
I figured this out, will be in v17 or v18, but within a couple of months. Stay tuned!

**Comment by ffflorian** [comment]
@fcturner 
Great, I'm looking forward to it!

**Comment by fcturner** [comment]
This will be implemented with the release of ownCloud 9, due to https://github.com/owncloud/core/issues/19331. So older versions of ownCloud will not be able to support my future version which contains sharing.

**Comment by fcturner** [comment]
(release date of OC9 is March 8th)

**Comment by rullzer** [comment]
Note that the new sharing work is for files only.
I suggest you setup you own sharing database for your app.

**Comment by fcturner** [comment]
:hushed: Never thought of that! Great idea!

**Comment by fcturner** [comment]
WORK IN PROGRESS:
```sql
-- CHECK IF USERS ARE ONLY ALLOWED TO SHARE ITEMS WITH USERS WITHIN THEIR OWN GROUPS
SELECT 
	configvalue
FROM
	oc_appconfig
WHERE
	configkey = 'shareapi_only_share_with_group_members';

-- IF 'no' THEN: GET ALL UID'S - REPLACE DISPLAY NAME WITH UID IF ABSENT
SELECT 
	uid,
	IF(displayname IS NULL,
		uid,
		displayname) AS displayname
FROM
	oc_users;

-- IF 'yes' THEN: ONLY GET UID'S FROM GROUPS WHERE CURRENT USER IS MEMBER OF
SELECT DISTINCT
	displaynames.uid, displaynames.displayname
FROM
	oc_group_user AS users
		LEFT JOIN
	(SELECT 
		uid,
			IF(displayname IS NULL, uid, displayname) AS displayname
	FROM
		oc_users) AS displaynames ON users.uid = displaynames.uid
WHERE
	gid IN (SELECT DISTINCT
			gid
		FROM
			oc_group_user
		WHERE
			uid = 'uid_that_i_logged_in_with');
```

**Comment by CirKu17** [comment]
+1 for this feature, would kick lastpass ass hard.

**Comment by morriswinkler** [comment]
ok what about public private key encryption, so you could implement multi user targeted encrypted data as GPG does it, it creates a one time pad to encrypt the data, than it uses the public key off every recipient user and encrypts the one time pad with that key and adds it to the encrypted data header, once done for all users it deletes the one time pad and the only way to get to the one time pad it with a private key of one of the recipient users.

so any recipient user can share that key again, since he can decrypt the one time pad encrypt it again with the target user public key and add it to the header, of course sharing restrictions can only be managed by the owncloud sharing infrastructure. 

i found a js library that implements all of the heavy lifting https://github.com/openpgpjs/openpgpjs, 

there readme states that:

* If the user's browser supports native WebCrypto via the window.crypto.subtle api, this will be used.

so this is good since the private key is not necessarily stored in local-storage

they have also undergone two independent security audits, that is good to .

**Comment by morriswinkler** [comment]
Just to make that clear, if you use a javascript library there would be never any unencrypted data on the server or the network, all the magic happens within the clients browser. Further you would have a consisting codebase that can be used for browser plugins.

**Comment by fcturner** [comment]
@ronoliverclarin @ffflorian @jasonfharris @rullzer @CirKu17 @IzK666 

**HURRAH!**

Just finished the sharing option!! Please down and test from here: https://github.com/fcturner/passwords/tree/sharing.
* Direct zip: https://github.com/fcturner/passwords/archive/sharing.zip
* Direct tarball: https://github.com/fcturner/passwords/archive/sharing.tar.gz

Rename the app folder to **passwords** and enjoy (hopefully). I will release it this or next week.

**Comment by fcturner** [comment]
@ib54003, maybe useful for you too, since you're looking for a password manager that can share passwords between users. This is implemented, now being tested and will be released within a couple of days. This app started last June and has had 19 releases already. See my comment above for links in ZIP and TAR.GZ format.

Screenshot (click to enlarge):
![Sharing](https://raw.githubusercontent.com/fcturner/passwords/master/img/screenshot2.PNG)

**Comment by ib54003** [comment]
@fcturner thanks for the hint, I'll try.

**Comment by fcturner** [comment]
Implemented in v18.
