### ISSUE TITLE
Passwords not Working on ownCloud 8.1.1

### ISSUE THREAD

**Issue by kneiser** [fcturner/passwords#59]
With the release of ownCloud 8.1.1 I installed what I "thought" was "Passwords   8.0.11". It would not work in this ownCloud release. In the end I found the culprit. When initiating a download on the ownCloud apps store by clicking on the "download" button the ZIP file downloaded contains "Passwords   8.0.12". In the body of the text in the apps store there is a link "https://github.com/fcturner/passwords/archive/8.0.11.zip" which is pointing to the correct version "Passwords   8.0.11", this one works in the current ownCloud 8.1.1 release.  I manually looked at the Github releases and noticed the there is a  "Passwords   8.0.12" present. When "Passwords   8.0.12" is installed and a user tries to use the apps, nothing happens when trying to add a new password.

**Comment by fcturner** [comment]
Hello, thanks for your input.

In fact, this has other reasons. 
ownCloud decided to create a way of installing apps from their app store, which totally kills the way GitHub works with its version system. Without creating a release on GitHub, the master version is always the latest. I made some edits to 8.0.11 and didn't draft a new release yet, because 8.0.12 is not yet finished. So when you download the zip from GitHub directly, you download the master, which is (partly) version 8.0.12 as of today.

So, why is this not working for you?
As stated in issue #56, downloads directly from the app store are not working, because I refuse to support their awful way of letting me implement this with every single version. I wrote that on the readme on the master to, so you should have read it.

For now, just download 8.0.11 or the master (they should both be fine) and install them manually.

Please let me know if this works for you.

**Comment by fcturner** [comment]
Fixed as of 8.0.12.
